#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>
#include <time.h>

void swap(int *arr, int i, int j)
{
    int t = arr[i];
    arr[i] = arr[j];
    arr[j] = t;
}

void quicksort(int *arr, int middle, int n)
{
    int pivot, j, i;
    if (n <= 1)
        return;
    pivot = arr[middle + n / 2];
    swap(arr, middle, middle + n / 2);
    j = middle;
    for (i = middle + 1; i < middle + n; i++)
        if (arr[i] < pivot)
        {
            j++;
            swap(arr, i, j);
        }
    swap(arr, middle, j);
    quicksort(arr, middle, j - middle);
    quicksort(arr, j + 1, middle + n - j - 1);
}

int *merge(int *arr1, int n1, int *arr2, int n2)
{
    int *rez = (int *)malloc((n1 + n2) * sizeof(int));
    int i = 0;
    int j = 0;
    int k;
    for (k = 0; k < n1 + n2; k++)
    {
        if (i >= n1)
        {
            rez[k] = arr2[j];
            j++;
        }
        else if (j >= n2)
        {
            rez[k] = arr1[i];
            i++;
        }
        else if (arr1[i] < arr2[j])
        {
            rez[k] = arr1[i];
            i++;
        }
        else
        {
            rez[k] = arr2[j];
            j++;
        }
    }
    return rez;
}
void print1(int arr[], int size)
{
    int i;
    for (i = 0; i < size; i++)
        printf("%d ", arr[i]);
    printf("\n");
}

int main1(int argc, char **argv)
{
    int n, i=0, nranks, rank, *arr, *firstPart, *secondPart, step, o, c, s;
    char fakeArray;
    MPI_Status status;
    MPI_Init(&argc, &argv);
    MPI_Comm_size(MPI_COMM_WORLD, &nranks);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);

    if (rank == 0)
    {
        printf("Length of array: ");
        scanf("%d", &n);
        c = (n % nranks != 0) ? n / nranks + 1 : n / nranks;
        arr = (int *)malloc(nranks * c * sizeof(int));
        printf("Print 'f' for autogenerated array or input the array");
        scanf(" %c", &fakeArray);
        if (fakeArray == 'f')
        {
            for (int i = 0; i < n; i++)
            {
                arr[i] = rand() % 100;
            }
            printf("Unsorted array: ");
            print1(arr, n);
        }
        else
        {
            for (int i = 0; i < n; i++)
            {
                printf("arr[%d]= ", i);
                scanf("%d", &arr[i]);
            }

        }

    }
    MPI_Barrier(MPI_COMM_WORLD);
    MPI_Bcast(&n, 1, MPI_INT, 0, MPI_COMM_WORLD);
    c = (n % nranks != 0) ? n / nranks + 1 : n / nranks;
    firstPart = (int *)malloc(c * sizeof(int));
    MPI_Scatter(arr, c, MPI_INT, firstPart, c, MPI_INT, 0, MPI_COMM_WORLD);
    free(arr);
    arr = NULL;
    s = (n >= c * (rank + 1)) ? c : n - c * rank;
    quicksort(firstPart, 0, s);
    for (step = 1; step < nranks; step = 2 * step)
    {
        if (rank % (2 * step) != 0)
        {
            MPI_Send(firstPart, s, MPI_INT, rank - step, 0, MPI_COMM_WORLD);
            break;
        }
        if (rank + step < nranks)
        {
            o = (n >= c * (rank + 2 * step)) ? c * step : n - c * (rank + step);
            secondPart = (int *)malloc(o * sizeof(int));
            MPI_Recv(secondPart, o, MPI_INT, rank + step, 0, MPI_COMM_WORLD, &status);
            arr = merge(firstPart, s, secondPart, o);
            free(firstPart);
            free(secondPart);
            firstPart = arr;
            s = s + o;
        }
    }
    if (rank == 0)
    {
        printf("Sorted array: ");
        print1(arr, n);
    }
    MPI_Finalize();
    return 0;
}

